apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
    version: v1
  name: devsecops
  namespace: default
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: devsecops
      # version: v1
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devsecops
        version: v1
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: replace
        name: devsecops-container
        imagePullPolicy: IfNotPresent
        - containerPort: 8090
          # protocol: TCP
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          capabilities:
            drop:
             - NET_RAW
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
  - port: 8080
    name: tcp-devsecops
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
    version: v1
  type: ClusterIP